import { ColorScheme, ThemeData } from "@app/material";
import { activeSeed } from "./catalog.js";

function withAlpha(color, alpha) {
  return `#${alpha}${color.replace("#", "").slice(0, 6)}`;
}

export function appTheme(model, brightness) {
  const seed = activeSeed(model);
  const dark = brightness === "dark";
  const surface = dark ? "#141218" : "#fffbfe";
  const onSurface = dark ? "#e6e0e9" : "#1d1b20";
  const surfaceContainer = dark ? "#211f26" : "#f3edf7";
  const outline = dark ? "#938f99" : "#79747e";
  const primary = seed.color;
  return ThemeData({
    useMaterial3: model.useMaterial3,
    useSystemColors: false,
    materialTapTargetSize: "shrinkWrap",
    platform: "macos",
    visualDensity: "comfortable",
    brightness,
    colorScheme: ColorScheme.fromSeed({
      seedColor: seed.color,
      brightness,
    }),
    primaryColorDark: dark ? "#80cbc4" : "#003737",
    primaryColorLight: dark ? "#003737" : "#80cbc4",
    secondaryHeaderColor: dark ? "#4a4458" : "#e8def8",
    unselectedWidgetColor: outline,
    fontFamilyFallback: ["SF Pro Text", "Roboto", "Arial"],
    scaffoldBackgroundColor: surface,
    actionIconTheme: {
      backButtonIcon: { icon: "arrow_back" },
      closeButtonIcon: { icon: "close" },
      drawerButtonIcon: { icon: "menu" },
      endDrawerButtonIcon: { icon: "menu" },
    },
    appBarTheme: {
      backgroundColor: surface,
      foregroundColor: onSurface,
      elevation: 0,
      scrolledUnderElevation: 1,
      centerTitle: false,
    },
    cardTheme: {
      color: surface,
      elevation: 1,
      margin: 0,
      shape: { borderRadius: 20 },
    },
    badgeTheme: {
      backgroundColor: primary,
      textColor: "#ffffff",
      smallSize: 8,
      largeSize: 20,
      textStyle: { fontSize: 11, fontWeight: "w700" },
      padding: { horizontal: 6 },
      alignment: "topRight",
      offset: [4, -4],
    },
    bannerTheme: {
      backgroundColor: surfaceContainer,
      surfaceTintColor: surface,
      shadowColor: dark ? "#66000000" : "#22000000",
      dividerColor: dark ? "#49454f" : "#e7e0ec",
      contentTextStyle: { color: onSurface, fontSize: 14 },
      elevation: 1,
      padding: { horizontal: 16, vertical: 12 },
      leadingPadding: { left: 16, right: 8 },
    },
    buttonTheme: {
      textTheme: "primary",
      minWidth: 64,
      height: 40,
      padding: { horizontal: 16 },
      shape: { borderRadius: 999 },
      layoutBehavior: "constrained",
      alignedDropdown: true,
      buttonColor: primary,
      disabledColor: dark ? "#49454f" : "#cac4d0",
      focusColor: withAlpha(primary, "1f"),
      hoverColor: withAlpha(primary, "14"),
      highlightColor: withAlpha(primary, "1f"),
      splashColor: withAlpha(primary, "1f"),
      materialTapTargetSize: "shrinkWrap",
    },
    dividerTheme: {
      color: dark ? "#49454f" : "#e7e0ec",
      space: 1,
      thickness: 1,
      radius: 1,
    },
    scrollbarTheme: {
      thumbVisibility: false,
      trackVisibility: { default: false, hovered: true },
      thickness: { default: 4, hovered: 8 },
      radius: 999,
      thumbColor: { default: primary, hovered: primary, dragged: primary },
      trackColor: { hovered: surfaceContainer },
      trackBorderColor: { hovered: outline },
      mainAxisMargin: 4,
      crossAxisMargin: 2,
      minThumbLength: 48,
      interactive: true,
    },
    datePickerTheme: {
      backgroundColor: surface,
      surfaceTintColor: surface,
      elevation: 2,
      shape: { borderRadius: 28 },
      headerBackgroundColor: primary,
      headerForegroundColor: "#ffffff",
      headerHeadlineStyle: { fontSize: 28, fontWeight: "w600" },
      headerHelpStyle: { fontSize: 14, fontWeight: "w500" },
      weekdayStyle: { color: outline, fontWeight: "w600" },
      dayForegroundColor: { selected: "#ffffff", default: onSurface },
      dayBackgroundColor: { selected: primary },
      dayOverlayColor: {
        hovered: withAlpha(primary, "14"),
        pressed: withAlpha(primary, "1f"),
      },
      dayShape: { borderRadius: 999 },
      todayForegroundColor: { default: primary },
      todayBorder: { color: primary, width: 1 },
      yearForegroundColor: { selected: "#ffffff", default: onSurface },
      yearBackgroundColor: { selected: primary },
      yearShape: { borderRadius: 999 },
      rangeSelectionBackgroundColor: withAlpha(primary, "24"),
      rangeSelectionOverlayColor: {
        hovered: withAlpha(primary, "14"),
        pressed: withAlpha(primary, "1f"),
      },
      dividerColor: dark ? "#49454f" : "#e7e0ec",
      inputDecorationTheme: {
        filled: true,
        fillColor: surfaceContainer,
        border: "outline",
      },
      cancelButtonStyle: { foregroundColor: primary },
      confirmButtonStyle: { foregroundColor: primary },
      toggleButtonTextStyle: { color: onSurface, fontWeight: "w600" },
      subHeaderForegroundColor: onSurface,
    },
    tooltipTheme: {
      decoration: {
        color: dark ? "#e6e0e9" : "#313033",
        borderRadius: 8,
      },
      textStyle: {
        color: dark ? "#313033" : "#ffffff",
        fontSize: 12,
      },
      padding: { horizontal: 10, vertical: 6 },
      margin: { all: 8 },
      preferBelow: false,
      waitDuration: 400,
      showDuration: { seconds: 2 },
    },
    listTileTheme: {
      iconColor: primary,
      textColor: onSurface,
      contentPadding: { horizontal: 16, vertical: 4 },
    },
    inputDecorationTheme: {
      filled: true,
      fillColor: surfaceContainer,
      border: "outline",
      contentPadding: { horizontal: 16, vertical: 12 },
    },
    textSelectionTheme: {
      cursorColor: primary,
      selectionColor: withAlpha(primary, "33"),
      selectionHandleColor: primary,
    },
    timePickerTheme: {
      backgroundColor: surface,
      elevation: 2,
      shape: { borderRadius: 28 },
      padding: { all: 24 },
      entryModeIconColor: primary,
      helpTextStyle: { color: outline, fontSize: 12, fontWeight: "w600" },
      hourMinuteColor: { selected: withAlpha(primary, "24"), default: surfaceContainer },
      hourMinuteTextColor: { selected: primary, default: onSurface },
      hourMinuteTextStyle: { fontSize: 48, fontWeight: "w500" },
      hourMinuteShape: { borderRadius: 16 },
      dayPeriodColor: { selected: withAlpha(primary, "24"), default: "transparent" },
      dayPeriodTextColor: { selected: primary, default: outline },
      dayPeriodBorderSide: { color: outline, width: 1 },
      dayPeriodShape: { borderRadius: 12 },
      dialBackgroundColor: surfaceContainer,
      dialHandColor: primary,
      dialTextColor: { selected: "#ffffff", default: onSurface },
      dialTextStyle: { fontSize: 14, fontWeight: "w600" },
      timeSelectorSeparatorColor: { selected: primary, default: outline },
      timeSelectorSeparatorTextStyle: { default: { fontSize: 44, color: outline } },
      inputDecorationTheme: {
        filled: true,
        fillColor: surfaceContainer,
        border: "outline",
      },
      cancelButtonStyle: { foregroundColor: primary },
      confirmButtonStyle: { foregroundColor: primary },
    },
    toggleButtonsTheme: {
      textStyle: { fontSize: 14, fontWeight: "w600" },
      constraints: { minWidth: 44, minHeight: 40 },
      color: onSurface,
      selectedColor: primary,
      disabledColor: dark ? "#49454f" : "#cac4d0",
      fillColor: withAlpha(primary, "1f"),
      focusColor: withAlpha(primary, "1f"),
      highlightColor: withAlpha(primary, "14"),
      hoverColor: withAlpha(primary, "14"),
      splashColor: withAlpha(primary, "1f"),
      borderColor: outline,
      selectedBorderColor: primary,
      disabledBorderColor: dark ? "#49454f" : "#cac4d0",
      borderRadius: 999,
      borderWidth: 1,
    },
    searchBarTheme: {
      backgroundColor: surfaceContainer,
      surfaceTintColor: surface,
      elevation: 0,
      shape: { borderRadius: 28 },
      side: { color: dark ? "#49454f" : "#cac4d0", width: 1 },
      padding: { horizontal: 16 },
      textStyle: { color: onSurface, fontSize: 16 },
      hintStyle: { color: dark ? "#cac4d0" : "#49454f", fontSize: 16 },
      constraints: { minHeight: 56 },
    },
    searchViewTheme: {
      backgroundColor: surface,
      surfaceTintColor: surface,
      elevation: 2,
      shape: { borderRadius: 28 },
      headerHeight: 64,
      headerTextStyle: { color: onSurface, fontSize: 16 },
      headerHintStyle: { color: dark ? "#cac4d0" : "#49454f", fontSize: 16 },
      dividerColor: dark ? "#49454f" : "#e7e0ec",
      padding: { horizontal: 8, bottom: 8 },
      barPadding: { horizontal: 8, top: 8 },
    },
    navigationRailTheme: {
      backgroundColor: surface,
      selectedIconTheme: { color: primary },
      selectedLabelTextStyle: { color: primary, fontWeight: "w600" },
      minWidth: 76,
    },
    navigationBarTheme: {
      backgroundColor: surface,
      indicatorColor: dark ? "#4a4458" : "#e8def8",
      labelBehavior: "alwaysShow",
    },
    snackBarTheme: {
      behavior: "floating",
      showCloseIcon: true,
    },
    dialogTheme: {
      backgroundColor: surface,
      shape: { borderRadius: 28 },
    },
    bottomSheetTheme: {
      backgroundColor: surface,
      showDragHandle: true,
      shape: { borderRadius: 28 },
    },
    filledButtonTheme: {
      style: {
        shape: { borderRadius: 999 },
      },
    },
    outlinedButtonTheme: {
      style: {
        shape: { borderRadius: 999 },
      },
    },
  });
}

export function schemeFor(seed, brightness) {
  const dark = brightness === "dark";
  const primary = seed.color;
  return dark
    ? {
        primary,
        onPrimary: "#381e72",
        primaryContainer: "#4f378b",
        onPrimaryContainer: "#eaddff",
        primaryFixed: "#eaddff",
        onPrimaryFixed: "#21005d",
        primaryFixedDim: "#d0bcff",
        onPrimaryFixedVariant: "#4f378b",
        secondary: "#ccc2dc",
        onSecondary: "#332d41",
        secondaryContainer: "#4a4458",
        onSecondaryContainer: "#e8def8",
        secondaryFixed: "#e8def8",
        onSecondaryFixed: "#1d192b",
        secondaryFixedDim: "#ccc2dc",
        onSecondaryFixedVariant: "#4a4458",
        tertiary: "#efb8c8",
        onTertiary: "#492532",
        tertiaryContainer: "#633b48",
        onTertiaryContainer: "#ffd8e4",
        tertiaryFixed: "#ffd8e4",
        onTertiaryFixed: "#31111d",
        tertiaryFixedDim: "#efb8c8",
        onTertiaryFixedVariant: "#633b48",
        error: "#f2b8b5",
        onError: "#601410",
        errorContainer: "#8c1d18",
        onErrorContainer: "#f9dedc",
        surfaceDim: "#141218",
        surface: "#141218",
        surfaceBright: "#3b383e",
        surfaceContainerLowest: "#0f0d13",
        surfaceContainerLow: "#1d1b20",
        surfaceContainer: "#211f26",
        surfaceContainerHigh: "#2b2930",
        surfaceContainerHighest: "#36343b",
        onSurface: "#e6e0e9",
        onSurfaceVariant: "#cac4d0",
        outline: "#938f99",
        outlineVariant: "#49454f",
        shadow: "#000000",
        scrim: "#000000",
        inverseSurface: "#e6e0e9",
        onInverseSurface: "#322f35",
        inversePrimary: "#6750a4",
      }
    : {
        primary,
        onPrimary: "#ffffff",
        primaryContainer: "#eaddff",
        onPrimaryContainer: "#21005d",
        primaryFixed: "#eaddff",
        onPrimaryFixed: "#21005d",
        primaryFixedDim: "#d0bcff",
        onPrimaryFixedVariant: "#4f378b",
        secondary: "#625b71",
        onSecondary: "#ffffff",
        secondaryContainer: "#e8def8",
        onSecondaryContainer: "#1d192b",
        secondaryFixed: "#e8def8",
        onSecondaryFixed: "#1d192b",
        secondaryFixedDim: "#ccc2dc",
        onSecondaryFixedVariant: "#4a4458",
        tertiary: "#7d5260",
        onTertiary: "#ffffff",
        tertiaryContainer: "#ffd8e4",
        onTertiaryContainer: "#31111d",
        tertiaryFixed: "#ffd8e4",
        onTertiaryFixed: "#31111d",
        tertiaryFixedDim: "#efb8c8",
        onTertiaryFixedVariant: "#633b48",
        error: "#b3261e",
        onError: "#ffffff",
        errorContainer: "#f9dedc",
        onErrorContainer: "#410e0b",
        surfaceDim: "#ded8e1",
        surface: "#fffbfe",
        surfaceBright: "#fffbfe",
        surfaceContainerLowest: "#ffffff",
        surfaceContainerLow: "#f7f2fa",
        surfaceContainer: "#f3edf7",
        surfaceContainerHigh: "#ece6f0",
        surfaceContainerHighest: "#e6e0e9",
        onSurface: "#1d1b20",
        onSurfaceVariant: "#49454f",
        outline: "#79747e",
        outlineVariant: "#cac4d0",
        shadow: "#000000",
        scrim: "#000000",
        inverseSurface: "#322f35",
        onInverseSurface: "#f5eff7",
        inversePrimary: "#d0bcff",
      };
}
